In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [7]:
companies = pd.read_csv("fortune1000-final.csv", encoding = 'unicode_escape')

In [10]:
companies.head()

,rank,title,Previous Rank,Revenues ($M),Revenue Change,Profits ($M),Profit Change,Assets ($M),Mkt Value as of 3/29/18 ($M),Employees,CEO,CEO Title,Sector,Industry,Years on Fortune 500 List,City,State,Latitude,Longitude
0,1,Walmart,1,"$500,343",3.00%,"$9,862.00",-27.70%,"$204,522","$263,563","2,300,000",C. Douglas McMillon,"President, Chief Executive Officer & Director",Retailing,General Merchandisers,24,Bentonville,AR,36.372854,-94.208817
1,2,Exxon Mobil,4,"$244,363",17.40%,"$19,710.00",151.40%,"$348,691","$316,157","71,200",Darren W. Woods,Chairman & Chief Executive Officer,Energy,Petroleum Refining,24,Irving,TX,32.814018,-96.948894
2,3,Berkshire Hathaway,2,"$242,137",8.30%,"$44,940.00",86.70%,"$702,095","$492,008","377,000",Warren E. Buffett,"Chairman, President & Chief Executive Officer",Financials,Insurance: Property and Casualty (Stock),24,Omaha,NE,41.256537,-95.934503
3,4,Apple,3,"$229,234",6.30%,"$48,351.00",5.80%,"$375,319","$851,318","123,000",Timothy D. Cook,Chairman & Chief Executive Officer,Technology,"Computers, Office Equipment",24,Cupertino,CA,37.322998,-122.032182
4,5,UnitedHealth Group,6,"$201,159",8.80%,"$10,558.00",50.50%,"$139,058","$207,080","260,000",David S. Wichmann,Chairman & Chief Executive Officer,Health Care,Health Care: Insurance and Managed Care,24,Minnetonka,MN,44.921184,-93.468749